org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Djava.awt.headless=true
org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=daemon
ksp.incremental=false
googleServices.missing.passthrough=true
android.disallowKotlinSourceSets=false
